### ISSUE TITLE
Cannot import 'Colony'

### ISSUE THREAD

**Issue by brett18618** [Engineero/honeybee#8]
Hi, thanks for your work first. When I ran "from honeybee import Colony", I got the ImportError: cannot import name 'Colony' from 'honeybee'.
Do you have any solution for it?

**Comment by Engineero** [comment]
The utility isn't finished yet. I started it as kind of a side project and I haven't gotten around to making it fully functional. If you would like to contribute you are welcome to do so! Otherwise I am not sure when I will get around to completing it unfortunately.

**Comment by Engineero** [comment]
On second thought, this looks like it shouldn't be happening regardless. I'll take a look. I might just have to update the __init__.py file in the main application folder.

**Comment by Engineero** [comment]
Import should now be fixed in version 0.1.0a4 on the master branch. Let me know if that doesn't work. I think the functionality is still not fully implemented. I will try to get back around to that soon.

**Comment by brett18618** [comment]
Thank you for your reply. But it still doesn't work. I noticed you add a
line of code in the init.py on Github, but when I ran 'pip install
honeybee", the init.py file still was the original one which didn't have
the code of import Colony.

**Comment by Engineero** [comment]
Oh right, I don't have it pushing to pypi automatically. I will try to figure that process out again and let you know when I do.

**Comment by Engineero** [comment]
OK, the new release is live on PyPi. Try `pip install --upgrade honeybee` and see if your problem is fixed. I am going to close this for now, but feel free to reopen if that didn't do it.

And continuing disclaimer: I'm pretty sure I never finished the algorithm before I set it aside, so it may not do much of anything yet. I will try to get back into it and finish it up soon.
